### ISSUE TITLE
pac paportal upload deploymentProfile duplicating values rather than overriding

### ISSUE THREAD

**Issue by flyfishMT** [microsoft/powerplatform-vscode#185]
This may be user error, but from all the [documentation](https://docs.microsoft.com/en-us/power-apps/maker/portals/power-apps-cli#use-deployment-profile) I have read, the deployment profile values are supposed to OVERRIDE the original value.  What I see, is it deploys them both, and whatever uses the value doesn't always choose the deployment profile value.  I would expect only the value in the deployment profile to be used.  Should I delete the original value from the sitesettings.yml file?  I didn't see any documentation say to do that.

/portal/deployment-profiles/dev.deployment.yml

```
adx_sitesetting:
- adx_name: Authentication/OpenIdConnect/AAD-B2C_1/Caption
  adx_sitesettingid: e91069f0-92a4-ec11-983f-000d3a58b83c
  adx_value: Azure AD B2C DEV
```

/portal/sitesetting.yml:

```
...
- adx_name: Authentication/OpenIdConnect/AAD-B2C_1/Caption
  adx_sitesettingid: e91069f0-92a4-ec11-983f-000d3a58b83c
  adx_value: Azure AD B2C
...
```
Command:
`
pac paportal upload --path "./portal" -dp dev`

Values in Portal Management App:

![image](https://user-images.githubusercontent.com/5473678/162526713-f5ad21c3-fd88-4b30-9168-a3cd8d9351cf.png)

Ennvironment: WSL2, bash, Ubuntu 20.04.4 LTS
Microsoft PowerPlatform CLI
Version: 1.14.2+g7205df7
